### ISSUE TITLE
JSON ⊂ YAML 题解中，“用一个输入同时获得两个 flag“ 有误

### ISSUE THREAD

**Issue by thinkingnull** [USTC-Hackergame/hackergame2023-writeups#47]
原文中
```
至于如何能用一个输入同时获得两个 flag，出题人认为最短的答案需要 13 个字符：{"":1e2,"":0}。
```
然而在网页终端中输入此答案，只能获取flag2，没有flag1。
```
Input your JSON: {"":1e2,"":0}
As JSON: {'': 0}
As YAML 1.1: {'': 0}
No flag1
Flag2: flag{.............}
```

**Comment by wuhang2003** [comment]
~~试了一下反过来的时候 `{"":0,"":1e2}` 就是对的，很奇怪（~~
写错了大草
![image](https://github.com/USTC-Hackergame/hackergame2023-writeups/assets/108316419/6e54aee6-2d65-49ed-8f4a-cfeb2b45c3a2)

**Comment by SmartHypercube** [comment]
写反了，尴尬。这样显然出不了 flag1
